import type { Metadata } from 'next'

import '../styles/globals.css'

import { Geist } from 'next/font/google'

const geistSans = Geist({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type RootLayoutProps = Readonly<{
  children: React.ReactNode
}>

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang='en' className={geistSans.className}>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
