import type { Metadata } from 'next'

import '../styles/globals.css'

import { Geist } from 'next/font/google'

const geistSans = Geist({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface LayoutProps {
  children: React.ReactNode
}

function Layout(props: LayoutProps) {
  const { children } = props

  return (
    <html lang='en' className={geistSans.className}>
      <body>{children}</body>
    </html>
  )
}

export default Layout
